name: Build and publish Docker image

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./demo/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/events-backend:latest
            ghcr.io/${{ github.repository_owner }}/events-backend:${{ github.sha }}

      - name: Image info
        run: |
          echo "Image pushed: ghcr.io/${{ github.repository_owner }}/events-backend:latest"
